services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "#Sahil@123"
      MYSQL_DATABASE: spring_ecom
    ports:
      - "3307:3306"    # ✅ Changed 3306 to 3307 on host side
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p#Sahil@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build: .
    container_name: ecom-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_NAME: spring_ecom
      DB_USERNAME: root
      DB_PASSWORD: "#Sahil@123"
    depends_on:
      mysql:
        condition: service_healthy
    command: ["sh", "-c", "sleep 20 && java -jar /app/app.jar"]

volumes:
  mysql-data: